name: Build and Publish to ghcr.io

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: s-vet

jobs:

  build-with-docker:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      packages: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and publish
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/waelbendhia/s-vet:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
