name: Build and Publish to ghcr.io

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: s-vet-web

jobs:

  build-web-app:
    name: Build wep app container and deploy
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      packages: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and publish
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/waelbendhia/s-vet-web:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build-server:
    name: Build server container and deploy
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      packages: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and publish
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/waelbendhia/s-vet:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    needs: [ build-web-app, build-server ]
    runs-on: ubuntu-latest
    steps:
    - name: Pull and restart containers
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          docker compose --project-directory $COMPOSE_DIRECTORY down
          docker compose --project-directory $COMPOSE_DIRECTORY pull
          docker compose --project-directory $COMPOSE_DIRECTORY -d up
